# Generated by Django 4.2.13 on 2024-06-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgodaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('loc', models.CharField(max_length=255)),
                ('link_url', models.URLField()),
                ('photo_url', models.URLField()),
                ('rate', models.FloatField()),
                ('platform', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '訂房網站資料',
                'verbose_name_plural': '訂房網站資料集',
                'db_table': 'all_rooms_data',
                'ordering': ['-price'],
            },
        ),
    ]
